#!/bin/bash
####################
### lockswitch #####
version="2.0" ######
### JustBrowsing ###
####################

_stock=$(awk NR==1 "/opt/justbrowsing/stock");
_random=$(/opt/justbrowsing/randpass $USER);

_altlock="/opt/justbrowsing/lock-gtkdialog";
_zenity=$(which zenity 2>/dev/null);
_gtkdialog=$(which gtkdialog 2>/dev/null);
if [ -z "$_zenity" -a -z "$_gtkdialog" ]; then
  echo "ERROR: GUI requires zenity OR gtkdialog";
  exit 1;
elif [ ! -z "$_zenity" -a -z "$_gtkdialog" ]; then
    zenity --question --title "Lock screen" --text "The password is:\n$_random" --ok-label="Lock" --cancel-label="Blank";
    input=$?;
elif [ -z "$_zenity" -a ! -z "$_gtkdialog" -a -f "$_altlock" ]; then
    input=$("$_altlock" "$_random" | grep ^EXIT= | awk -F = '{print $2}' | sed 's/"//g');
else
  if [ -z "$1" -o "$1" = "--zenity" ]; then
    zenity --question --title "Lock screen" --text "The password is:\n$_random" --ok-label="Lock" --cancel-label="Blank";
    input=$?;
  elif [ "$1" = "--gtkdialog" ]; then
    input=$("$_altlock" "$_random" | grep ^EXIT= | awk -F = '{print $2}' | sed 's/"//g');
  else
    echo "USAGE: $0 [--zenity|--gtkdialog]";
    exit 1;
  fi
fi
  

if [ "$input" = "0" ]; then
  echo -e "$_stock\n$_random\n$_random" | passwd;
  if [ -f "/usr/bin/wbar" -a -f "/usr/bin/i3lock-spy-wbar" ]; then
    /usr/bin/wbar &
    /usr/bin/i3lock-spy-wbar -n -p default -i $HOME/.i3/lockscreen.png;
    pkill wbar
  elif [ -f "/usr/bin/i3lock-spy" ]; then
    /usr/bin/i3lock-spy -n -p default -i $HOME/.i3/lockscreen.png;
  else
    /usr/bin/i3lock -n -p default -i $HOME/.i3/lockscreen.png;
  fi
  echo -e "$_random\n$_stock\n$_stock" | passwd;
else
  xset dpms force off
fi

rm $HOME/.locks/zenity.lock
